server.port=${SERVERS.PORT}
spring.datasource.url=${SPRING.DATASOURCES.URL}
spring.datasource.username=${SPRING.DATASOURCES.USERNAME}
spring.datasource.password=${SPRING.DATASOURCES.PASSWORD}
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver

#security
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING.EMAIL.USERNAME}
spring.mail.password=${SPRING.EMAIL.PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

jwt.secret=${JWT.SECRET}
jwt.accessTokenExpirationTime=${JWT.ACCESSTOKENEXPIRATIONTIME}
jwt.refreshTokenExpirationTime=${JWT.REFRESHTOKENEXPIRATIONTIME}
resetUrl=${RESETURL}
